using System.Collections.Generic;
using System.Text;
using UnityEditor;
using UnityEditor.Localization;
using UnityEngine;
using UnityEngine.Localization.Tables;

namespace Internal.Scripts.Import.Editor.Core
{
    public static class LocalizationKeysGenerator
    {
        private const string OutputPath =
            "Assets/Internal/Scripts/UI/Localization/Generated/LocKeys.gen.cs";

        private const string GeneratedNamespace =
            "Internal.Scripts.UI.Localization.Generated";

        [MenuItem("SPJ/Generate/LocalizationKeys")]
        public static void Generate()
        {
            var collections = LocalizationEditorSettings.GetStringTableCollections();

            var classes = new List<(string className, string tableName, List<(string constName, string key)> consts)>();

            foreach (var collection in collections)
            {
                string tableName = collection.TableCollectionName;
                string className = "Loc" + ImportHelpers.ToPascalCase(tableName);

                var consts = new List<(string constName, string key)>();
                var seen = new HashSet<string>(System.StringComparer.Ordinal);

                foreach (SharedTableData.SharedTableEntry entry in collection.SharedData.Entries)
                {
                    string key = entry.Key;
                    string constName = KeyToConstName(key);

                    if (!ImportHelpers.IsValidIdentifier(constName))
                    {
                        Debug.LogError($"[SPJ] LocalizationKeysGenerator: invalid identifier '{constName}' derived from key '{key}' in table '{tableName}'. Generation aborted.");
                        return;
                    }

                    if (!seen.Add(constName))
                    {
                        Debug.LogError($"[SPJ] LocalizationKeysGenerator: const name collision '{constName}' in table '{tableName}' (key '{key}'). Generation aborted.");
                        return;
                    }

                    consts.Add((constName, key));
                }

                classes.Add((className, tableName, consts));
            }

            string content = BuildSource(classes);
            ImportHelpers.EnsureDirectory(OutputPath);

            bool changed = ImportHelpers.WriteIfChanged(OutputPath, content);
            if (changed)
            {
                Debug.Log($"[SPJ] LocKeys.gen.cs updated ({OutputPath}).");
                AssetDatabase.Refresh();
            }
            else
            {
                Debug.Log("[SPJ] LocKeys.gen.cs is up to date.");
            }
        }

        private static string KeyToConstName(string key)
        {
            string[] segments = key.Split('.');
            var sb = new StringBuilder();
            for (int i = 0; i < segments.Length; i++)
            {
                if (i > 0) sb.Append('_');
                sb.Append(ImportHelpers.ToPascalCase(segments[i]));
            }
            return sb.ToString();
        }

        private static string BuildSource(List<(string className, string tableName, List<(string constName, string key)> consts)> classes)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#pragma warning disable CS1591");
            sb.AppendLine($"namespace {GeneratedNamespace}");
            sb.AppendLine("{");

            foreach (var (className, tableName, consts) in classes)
            {
                sb.AppendLine($"    public static class {className}");
                sb.AppendLine("    {");
                sb.AppendLine($"        public const string Table = \"{tableName}\";");

                foreach (var (constName, key) in consts)
                    sb.AppendLine($"        public const string {constName} = \"{key}\";");

                sb.AppendLine("    }");
            }

            sb.AppendLine("}");
            return sb.ToString();
        }
    }
}
